#!/usr/bin/env python3
import subprocess
import time

# this will run 15 seeds each on their own job using knf2cnf for the boundary points up to n=180 (given by runBounds.sh)

RUN_SCRIPT = "../runBounds.sh"
SBATCH_TIME = "72:00:00"

COMMON_ARGS = [
    "-k", "7",
    "-l", "0",
    "-s", "1",
    "-v", "1",
    "-a", "0",
    "-c", "0",
    "-b", "2",
    "-f", "0",
    "-t", "7200",
]

SEEDS = range(1,16)  

for seed in SEEDS:
    jobname = f"r{seed}"
    cmd = [
        "sbatch",
        f"--time={SBATCH_TIME}",
        f"--job-name={jobname}",
        RUN_SCRIPT,
    ] + COMMON_ARGS + ["-r", str(seed)] # no encoding used = knf2cnf (sequential counter)
    print(" ".join(cmd))
    out = subprocess.check_output(cmd, text=True).strip()
    print(" ->", out)
    time.sleep(1)
